Create 1408.5593.pdf.md
arxivwiki/arxivwiki pull request #30
Opened 2021-06-11 08:24 UTC by SakibulIslamSazzad

Event-based sequencing to implement MZI
Path-choice delay problem is satisfied in here.

2021-06-11 18:57 UTC, marwahaha requested changes

2021-06-11 18:57 UTC, marwahaha commented on pdf/1408.5593.pdf.md
> +With a python code, without any model following this paper generated all the related results for MZI.
I don't quite understand this sentence.

2021-06-12 06:29 UTC, SakibulIslamSazzad commented on pdf/1408.5593.pdf.md
> +With a python code, without any model following this paper generated all the related results for MZI.
Oh my apologies, this papers develop MZI from scratch actually. without any experimental/ some other help they did it theoretically To achieve that they developed a library based on python.

2021-06-18 22:40 UTC, merged

2021-06-18 22:40 UTC, marwahaha commented
Thank you!